### ISSUE TITLE
How to get the api_key

### ISSUE THREAD

**Issue by xd003** [shgew/cs-firewall-bouncer-docker#6]
Hi, I have a quick question regarding the `api_key` configuration. I'm using this container that runs in host networking mode, while my CrowdSec container is running inside the dedicated crowdsec Docker network. Given this setup, I'm a bit unsure about what value should be used for the `api_key`, and how the communication between the containers should be handled. Could you clarify the recommended approach in this case?

**Comment by xd003** [comment]
Okey, i found the solution for above
In crowdsec ports section, i added the following to make it available on localhost
```
    ports:
      - 127.0.0.1:9876:8080 # port mapping for local firewall bouncers
```

Then in `api_url`, i used the following - `http://127.0.0.1:9876/`

Is there a way to ensure that this containerized crowdsec firewall bouncer is working correctly ? For what its worth, when i exec into crowdsec container and run `cscli bouncers list`, it does get listed

```
/ # cscli bouncers list
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Name             IP Address  Valid  Last API pull         Type                             Version                                           Auth Type
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 crowdsecBouncer  172.19.0.2  ✔️     2025-06-17T14:21:02Z  Crowdsec-Bouncer-Traefik-Plugin  1.X.X                                             api-key
 FirewallBouncer  172.19.0.1  ✔️     2025-06-17T14:21:35Z  crowdsec-firewall-bouncer        v0.0.33-cb8b3e3c654499f745ff487eb1c327d7234a533f  api-key
```

**Comment by LaurenceJJones** [comment]
Seems to be connecting, however, a key thing to point out if your application is exposed via Docker/Podman it uses NAT to bypass the `input` chain so if you use the default configuration you need to enable `DOCKER-USER` within https://github.com/crowdsecurity/cs-firewall-bouncer/blob/9783ec8442d7aa11b8d092bd0bfd57edc39bb834/config/crowdsec-firewall-bouncer.yaml#L30-L33 for the remediation to place rules where it interrupts Docker connections.

**Comment by xd003** [comment]
Thanks for confirming. I appreciate that, especially since I didn’t even have that option in my config to begin with. I'm not very experienced with networking and don’t fully understand all the technical details yet, so I’m just aiming to get a stable, functional setup while gradually learning more along the way.
In my case, I’m using `nftables` in backend mode (just because i read its modern). When I saw the option `iptables_chains:`, it seemed like it was specific to iptables, so I removed it from my configuration.
Since this involves security, I just want to double-check that I’m not overlooking anything important. Here’s my complete config. I’d really appreciate it if you could take a quick look and let me know if there’s anything I should add, remove, or modify. 

Lastly, do i also need to have ufw (iptables/nftable) installed on my ubuntu host for everything to work ?

```
mode: nftables
update_frequency: 10s
log_mode: file
log_dir: /var/log/
log_level: info
log_compression: true
log_max_size: 100
log_max_backups: 3
log_max_age: 30
api_url: http://127.0.0.1:9876/
api_key: ${API_KEY}
insecure_skip_verify: false
disable_ipv6: false
deny_action: DROP
deny_log: false
supported_decisions_types:
  - ban

nftables_hooks:
  - input
  - forward

nftables:
  ipv4:
    enabled: true
    set-only: false
    table: crowdsec
    chain: crowdsec-chain
    priority: -10
  ipv6:
    enabled: true
    set-only: false
    table: crowdsec6
    chain: crowdsec6-chain
    priority: -10

# Edited config to add below as per your advise
iptables_chains:
  - INPUT
  - DOCKER-USER
```
